import * as f from '../fixtures';

f.test.describe.serial('Documentation - Upload and Download Document Tests', () => {
    let testDocumentName: string;
    let isDocumentUploaded = false;

    f.test.beforeEach(async ({ loginPage, homePage, documentationPage }) => {
        await loginPage.login(f.adminProfessionalUser.username, f.adminProfessionalUser.password);
        await homePage.validateHomePageIsOpened();
        await documentationPage.dismissModal();
        await documentationPage.selectQADevCompany();
        await documentationPage.page.waitForLoadState('networkidle');
        await documentationPage.navigateToDocumentation();
    });

    f.test('should upload a new document and verify it appears in the list @smoke @regression', async ({ documentationPage }) => {
        // Generating a unique document name for the test run
        const uniqueId = new Date().getTime();
        testDocumentName = `test_document_${uniqueId}.txt`;
        const fileContent = `This is a test document automatically generated by playwright tests at timestamp ${uniqueId}`;

        await documentationPage.uploadDocument(testDocumentName, fileContent);
        await documentationPage.verifyUploadSuccessAlert();
        await documentationPage.searchDocument(testDocumentName);
        await documentationPage.verifyDocumentInTable(testDocumentName);
        isDocumentUploaded = true;
    });

    f.test('should download the uploaded document and verify in File Manager @smoke @regression', async ({ documentationPage }) => {
        f.test.skip(!isDocumentUploaded, 'Skipping because the upload test did not pass');

        // Download the document
        await documentationPage.downloadDocument(testDocumentName);
        await documentationPage.verifyDownloadInFileManager(testDocumentName);

        // Cleanup: delete the document after verifying download
        await documentationPage.deleteDocument(testDocumentName);
        await documentationPage.verifyDeleteSuccessAlert();
    });
});
