import * as f from '../fixtures';

f.test.describe('Documentation - Upload Document Tests', () => {
    let testDocumentName: string;

    f.test.beforeEach(async ({ loginPage, homePage, documentationPage }) => {
        await loginPage.login(f.adminProfessionalUser.username, f.adminProfessionalUser.password);
        await homePage.validateHomePageIsOpened();
        await documentationPage.dismissModal();
        await documentationPage.selectQADevCompany();
        await documentationPage.page.waitForLoadState('networkidle');
        await documentationPage.navigateToDocumentation();
    });

    f.test.afterEach(async ({ documentationPage }) => {
        if (testDocumentName) {
            await documentationPage.deleteDocument(testDocumentName);
            await documentationPage.verifyDeleteSuccessAlert();
        }
    });

    f.test('should upload a new document and verify it appears in the list @smoke @regression', async ({ documentationPage }) => {
        // Generating a unique document name for the test run
        const uniqueId = new Date().getTime();
        testDocumentName = `test_document_${uniqueId}.txt`;
        const fileContent = `This is a test document automatically generated by playwright tests at timestamp ${uniqueId}`;

        await documentationPage.uploadDocument(testDocumentName, fileContent);
        await documentationPage.verifyUploadSuccessAlert();
        await documentationPage.searchDocument(testDocumentName);
        await documentationPage.verifyDocumentInTable(testDocumentName);
    });
});
